version: '3.8'

services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    restart: unless-stopped
    environment:
      - STORAGE_DIR=/app/storage
      - SERVER_PORT=3001
    volumes:
      - ./storage:/app/storage
    networks:
      - wwiz-network
    expose:
      - "3001"

  nginx:
    image: nginx:alpine
    container_name: wwiz-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - anythingllm
    networks:
      - wwiz-network

  certbot:
    image: certbot/certbot
    container_name: wwiz-certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  wwiz-network:
    driver: bridge

volumes:
  storage: